spring.application.name=reco
spring.datasource.url=jdbc:postgresql://ep-spring-hat-ap8fieye-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_U2WQzI0ECMrS&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_U2WQzI0ECMrS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url=jdbc:mysql://localhost:3306/recobd?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
